---
output: github_document
---



```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

```
# butteR


butteR can be used to smooth out the analysis and visualization of spatial survey data collected using odk. ButteR mainly consists of convenient wrappers and pipelines for the survey, srvyr, sf, and rtree packages.

## Installation

You can install the the development version from [GitHub](https://github.com/) with:


``` {r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("zackarno/butteR")
## Example
```




```{r example}
library(butteR)
library(dplyr)
lon<-runif(min=88.00863,max=92.68031, n=100)
lat<-runif(min=20.59061,max=26.63451, n=100)
strata_options<-LETTERS[1:8]

#make a simulated dataset
pt_data<-data.frame(lon=lon, lat=lat, strata=sample(strata_options,1000, replace=TRUE))
sample_frame<-data.frame(strata=strata_options,sample_size=round(runif(10,100,n=8),0))

sampler_ouput<-butteR::stratified_sampler(sample.target.frame = sample_frame, 
                           sample.target.frame.strata = "strata",
                           sample.target.frame.samp.size = "sample_size",pt.data =pt_data,
                           pt.data.strata = "strata",pt.data.labels = "strata" ,write_kml = FALSE
                            )


```


  
  
  

